### ISSUE TITLE
Logo for dns-resolver-infra

### ISSUE THREAD

**Issue by worlwide** [publicarray/dns-resolver-infra#1]
Hello there. I design a logo in my free time. I want to design a logo for you. What do you think ? I want to contribute you.

**Comment by publicarray** [comment]
Hi, I'm not sure but I don't think a DNS resolver infrastructure needs a logo.
But I'm happy if you want to design one. We can put it in the Readme.md

**Comment by worlwide** [comment]
I hope you like it. What do you think ?

Different color variations are available.

![dns-alt](https://user-images.githubusercontent.com/40164336/41286674-efbf4696-6e48-11e8-968b-a9e43b8f2302.jpg)

**Comment by publicarray** [comment]
Nice work! I like the black or the blue solid one the most. I also wonder how it would look like if the colours where swapped. (the text in colour and the background transparent/white). The ones with a gradient remind me a bit of the 90s, Sorry I think gradients are out. If you know how to make a [Pull Request](https://help.github.com/articles/creating-a-pull-request/), you can create one so you get the correct attribution. For the web I recommend either a `png` or `svg` file.
Thank you for the logo!

**Comment by worlwide** [comment]
I sent a pr. 

https://github.com/publicarray/dns-resolver-infra/pull/2

**Comment by publicarray** [comment]
Thank you! merged.
