### ISSUE TITLE
https://doh.seby.io:8443 Connection refused

### ISSUE THREAD

**Issue by PeterDaveHello** [publicarray/dns-resolver-infra#18]
Error message from different tools:

```
An error occurred during a connection to doh.seby.io:8443. 
```

```
;; WARNING: can't connect to 45.76.113.31@8443(TCP)
;; ERROR: failed to query server doh.seby.io@8443(TCP)
```

```
curl: (7) Failed to connect to doh.seby.io port 8443 after 176 ms: Connection refused
```

Looks like there's a problem?

**Comment by PeterDaveHello** [comment]
It's interesting that the status on the UptimeRobot(https://stats.uptimerobot.com/qx96WC8LY0/783137078) looks good, and the port `443` also works.

Is it just because the documentation at https://dns.seby.io/ dated?

**Comment by publicarray** [comment]
Sorry yea I've got to update it. Just slammed at the moment with work. I'll have some time during the weekend to update it

**Comment by publicarray** [comment]
the website has been updated
