### ISSUE TITLE
Update for dnscrypt-server for k8s?

### ISSUE THREAD

**Issue by zoonderkins** [publicarray/dns-resolver-infra#21]
I try to follow along kubernetes setup but dnscrypt-server seems not yet have the yaml file.

**Comment by publicarray** [comment]
Sorry for the late reply, I was on holiday.

The k8 configuration hasn't been used for a long time as I found Docker compose is just simpler for this sort of setup. I remember I used k8 when there was uncertainty around docker compose support. I should probably get rid of the old files to avoid confusion.

**Comment by zoonderkins** [comment]
Okay got it.
