### ISSUE TITLE
Vultr DNS TLS Server

### ISSUE THREAD

**Issue by directnupe** [publicarray/dns-resolver-infra#6]
Dear  Sebastian,
Hello and I hope that you are well. Vultr DNS TLS Server ( 45.76.113.31 ) has Let's encrypt Certificate -
H13Su1659zEn0ZIblEShwjZO+M5gxKK2wXpVKQHgibM=  - expires in 7 days. I just wanted to let you know. Many providers renew prior to this. If you were aware - please forgive this message. today is 12-5-2019
Peace and Happy Holidays -
directnupe

**Comment by publicarray** [comment]
Hi 👋 Directnupe!

Thanks I've run the updater script (acme.sh) so the cert now renewed.
