### ISSUE TITLE
Let's Encrypt Certificates Renewal

### ISSUE THREAD

**Issue by directnupe** [publicarray/dns-resolver-infra#7]
Dear Madam / Sir,
Hello and I hope that you are well. First, I wish to thank you personally and 
on the behalf of all who value DNS PRIVACY. By running your excellent DNS
Servers we are able to keep our internet experience safe and secure. However,
I would like to avail you of the fact that the certificate for Vultr DNS TLS Server
( 45.76.113.31 ) and OVH DNS TLS Server ( 139.99.222.72 )  are due to expire on 
2020-02-09 and 2020-02-14 respectively today is 2020-02-06. Normally,
it is best to renew Let's Encrypt Certificates before this point. I would like to 
bring to your attention Certbot found here : https://certbot.eff.org/  This wonderful
website based tool automates the issuance and renewal of Let's Encrypt Certificates
for your DNS Privacy Servers. So - you might consider deploying Cerbot so as to make
it more easy to manage your certificates and keep us all the most secure as possible
while using your services.
Once again, thank you for your time, dedication and acumen in keeping us all safe
while deploying DNS Privacy.

Yours with Peace and Well Wishes,

directnupe

**Comment by publicarray** [comment]
👋 Hi @directnupe,
Thanks it makes me happy to know that it's been useful, I originally started this for my own personal use, when I started this there where hardly any servers in Australia that also valued privacy.

Thanks for reminding me, I use [acme.sh](acme.sh) but the renewal demon was not fully installed via docker. I have manually renewed the certificates and setup the renewal demon.
